### ISSUE TITLE
Dark mode docs unreadable, because of the colors

### ISSUE THREAD

**Issue by wahur666** [godotengine/godot-docs#3209]
Issue: 
Danger sections have tan background color, with white letters, it is unreadable

![kép](https://user-images.githubusercontent.com/9078042/75481334-2ac02c00-59a3-11ea-956f-d84b071db3cd.png)

Web page, where you can check it out:
https://docs.godotengine.org/en/3.2/tutorials/misc/running_code_in_the_editor.html

Solution: Black letters?

**Comment by clayjohn** [comment]
This was reported already in https://github.com/godotengine/godot-docs/issues/3135 and should have been fixed by https://github.com/godotengine/godot-docs/pull/3136. 

You may be reading a cached version of the doc.Can you try clearing your cache and reloading the page?

**Comment by wahur666** [comment]
Tried it, still not working as expected, in incognito mode, there is this problem too. How can I switch to light mode?

**Comment by Calinou** [comment]
I can confirm the issue is still present on that page. (I tried clearing my browser cache.)

It seems Read the Docs is late to pick up CSS changes from time to time. I suppose this will be fixed once the documentation is rebuilt a few times thanks to new commits.

**Comment by clayjohn** [comment]
@Calinou Actually its only present in 3.2 and stable. It looks like we just forgot to cherrypick your PR into the 3.2 branch.

**Comment by akien-mga** [comment]
Closing, I'll merge master in `stable` and `3.2` today (minus 4.0-specific changes).
