### ISSUE TITLE
Your First Game C# Missing _mobTypes variable declaration

### ISSUE THREAD

**Issue by gregoriB** [godotengine/godot-docs#3609]
**Issue description:**

The `_mobTypes` variable declaration part is totally absent from the C# example in the docs.  It's in the repo .rst file though.
```
var _mobTypes = GetNode<AnimatedSprite("AnimatedSprite").Frames.GetAnimationNames();
```

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#enemy-script

**Comment by Nimmda** [comment]
Already fixed in the latest docs. #3603 
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#enemy-script.

**Comment by gregoriB** [comment]
I'm still not seeing it.  Tried incognito windows and both chrome and FF.  Very odd.

**Comment by Nimmda** [comment]
Sry it is in the latest docs, I posted the wrong link. 
https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html

**Comment by gregoriB** [comment]
Yup there it is.  Thanks @Nimmda
